(() => {
  'use strict';
  const NS='http://www.w3.org/2000/svg';
  const byId=new Map(COUNTRIES.map(d=>[d.id,d]));
  const state={selected:'ind',mode:'cooperation',year:2026,activeRoles:new Set(Object.keys(ROLE_META)),trade:new Map()};
  const svg=document.getElementById('map'),panel=document.getElementById('panel'),select=document.getElementById('countrySelect'),yearSelect=document.getElementById('yearSelect'),modeControl=document.getElementById('modeControl'),legend=document.getElementById('legend');
  function node(name,attrs={}){const n=document.createElementNS(NS,name);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n;}
  function project(d){return [25+(d.lon+180)/360*950,30+(90-d.lat)/180*540];}
  function path(a,b,bend=.12){const p1=project(a),p2=project(b),dx=p2[0]-p1[0],dy=p2[1]-p1[1],m=[(p1[0]+p2[0])/2,(p1[1]+p2[1])/2],l=Math.hypot(dx,dy)||1,c=[m[0]-dy/l*Math.hypot(dx,dy)*bend,m[1]+dx/l*Math.hypot(dx,dy)*bend];return `M${p1[0]},${p1[1]} Q${c[0]},${c[1]} ${p2[0]},${p2[1]}`;}
  function visible(d){return d.kind==='anchor'||d.roles.some(r=>state.activeRoles.has(r));}
  function neighbor(id,s){return COOPERATION.some(d=>d.source&&((d.source===s&&d.target===id)||(d.target===s&&d.source===id)))||CORRIDORS.some(d=>(d.source===s&&d.target===id)||(d.target===s&&d.source===id));}
  function init(){
    const middle=COUNTRIES.filter(d=>d.kind==='middle').sort((a,b)=>a.name.localeCompare(b.name));
    const anchors=COUNTRIES.filter(d=>d.kind==='anchor').sort((a,b)=>a.name.localeCompare(b.name));
    select.innerHTML='<option value="">Overview</option><optgroup label="Middle powers">'+middle.map(d=>`<option value="${d.id}">${d.name}</option>`).join('')+'</optgroup><optgroup label="External anchors">'+anchors.map(d=>`<option value="${d.id}">${d.name}</option>`).join('')+'</optgroup>';
    select.value=state.selected;
    select.addEventListener('change',()=>{state.selected=select.value||null;draw();renderPanel();});
    yearSelect.addEventListener('change',()=>{state.year=+yearSelect.value;draw();renderPanel();});
    modeControl.addEventListener('click',e=>{const b=e.target.closest('button[data-mode]');if(!b)return;state.mode=b.dataset.mode;modeControl.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));copy();draw();});
    Object.entries(ROLE_META).forEach(([key,meta])=>{const x=document.createElement('span');x.className='legend-item';x.innerHTML=`<span class="legend-dot" style="background:${meta.color}"></span>${meta.label}`;x.addEventListener('click',()=>{if(state.activeRoles.has(key)&&state.activeRoles.size>1)state.activeRoles.delete(key);else state.activeRoles.add(key);x.classList.toggle('dim',!state.activeRoles.has(key));draw();});legend.appendChild(x);});
    copy();draw();renderPanel();
  }
  function copy(){const t=document.getElementById('mapTitle'),n=document.getElementById('mapNote');if(state.mode==='cooperation'){t.textContent='Formal and institutional cooperation';n.textContent='Dashed links show bilateral agreements; multilateral memberships appear in country profiles.';}else if(state.mode==='corridors'){t.textContent='Structural dependence and complementarity';n.textContent='Solid directional corridors are qualitative research codings, not bilateral customs values.';}else{t.textContent='Cooperation overlaid on structural dependence';n.textContent='Dashed links are agreements; solid links are coded supply-chain corridors.';}}
  function draw(){
    svg.innerHTML='';svg.setAttribute('viewBox','0 0 1000 625');
    const grid=node('g');for(let lon=-150;lon<=150;lon+=30){const x=25+(lon+180)/360*950;grid.appendChild(node('line',{x1:x,y1:30,x2:x,y2:570,class:'graticule'}));}for(let lat=-60;lat<=60;lat+=30){const y=30+(90-lat)/180*540;grid.appendChild(node('line',{x1:25,y1:y,x2:975,y2:y,class:'graticule'}));}svg.appendChild(grid);
    const links=[];if(state.mode==='cooperation'||state.mode==='both')COOPERATION.filter(d=>d.source&&d.year<=state.year).forEach(d=>links.push({...d,mode:'coop'}));if(state.mode==='corridors'||state.mode==='both')CORRIDORS.filter(d=>state.activeRoles.has(d.layer)).forEach(d=>links.push({...d,mode:'corridor'}));
    const lg=node('g');links.forEach((d,i)=>{const a=byId.get(d.source),b=byId.get(d.target),p=node('path',{d:path(a,b,i%2?-.11:.11),class:`link ${d.mode==='coop'?'coop':'corridor'}`,stroke:d.mode==='corridor'?ROLE_META[d.layer].color:'#0f6f8a','stroke-width':d.mode==='corridor'?1.2+d.intensity*.45:2.2,opacity:state.selected?((d.source===state.selected||d.target===state.selected)?.95:.08):.65});const title=node('title');title.textContent=d.mode==='coop'?`${d.title} (${d.year})`:`${a.name} → ${b.name}: ${d.label}`;p.appendChild(title);lg.appendChild(p);});svg.appendChild(lg);
    const ng=node('g');COUNTRIES.forEach(d=>{const [x,y]=project(d),r=d.kind==='anchor'?7.5:5.5+Math.sqrt(d.score)*.72,dim=!visible(d)||(state.selected&&d.id!==state.selected&&!neighbor(d.id,state.selected));const g=node('g',{class:`node ${d.kind}${d.id===state.selected?' selected':''}${dim?' dim':''}`,transform:`translate(${x},${y})`});g.appendChild(node('circle',{class:'ring',r:r+4,stroke:d.id===state.selected?ROLE_META[d.dominant].color:'#fff'}));g.appendChild(node('circle',{class:'core',r,fill:ROLE_META[d.dominant].color}));const text=node('text',{x:x>760?-(r+5):r+5,y:-r-1,'text-anchor':x>760?'end':'start'});text.textContent=d.name;g.appendChild(text);const title=node('title');title.textContent=d.headline;g.appendChild(title);g.addEventListener('click',()=>{state.selected=d.id;select.value=d.id;draw();renderPanel();});ng.appendChild(g);});svg.appendChild(ng);
  }
  function agreement(a){const meta=a.members?`${a.year} · multilateral · ${a.status}`:`${a.year} · ${a.type} · ${a.status}`;return `<div class="agreement"><a href="${a.url}" target="_blank" rel="noopener">${a.title}</a><div class="meta">${meta}</div><div class="detail">${a.detail}</div></div>`;}
  function exposure(x){return [['us','United States'],['china','China'],['eu','Europe'],['asia','Asian network']].map(([k,l])=>`<div class="exposure-row"><span>${l}</span><div class="bar"><span style="width:${x[k]*20}%"></span></div><strong>${x[k]}</strong></div>`).join('');}
  function tradeHtml(d){const k=`${d.id}-${state.year}`,v=state.trade.get(k);if(!d.code)return '<div class="method-banner">A single UN Comtrade reporter code is not used for this regional anchor.</div>';if(!v)return `<div class="metric-grid"><div class="metric"><div class="label">Exports</div><div class="value">—</div><div class="meta">HS 8542 · ${state.year}</div></div><div class="metric"><div class="label">Imports</div><div class="value">—</div><div class="meta">HS 8542 · ${state.year}</div></div></div><button class="load-trade" id="loadTrade">Load live UN Comtrade totals</button>`;if(v.error)return `<div class="method-banner">Live UN Comtrade data could not be loaded: ${v.error}. The coded research map remains available.</div><button class="load-trade" id="loadTrade">Retry live query</button>`;return `<div class="metric-grid"><div class="metric"><div class="label">Exports</div><div class="value">${money(v.exports)}</div><div class="meta">HS 8542 · ${state.year}</div></div><div class="metric"><div class="label">Imports</div><div class="value">${money(v.imports)}</div><div class="meta">HS 8542 · ${state.year}</div></div></div><button class="load-trade" id="loadTrade">Refresh live totals</button>`;}
  function renderPanel(){
    if(!state.selected){panel.innerHTML=`<h2>How to read the map</h2><p>This project treats semiconductor power as a network of specialized capabilities rather than a ranking of national self-sufficiency.</p><div class="summary-grid"><div class="summary-card"><strong>${COUNTRIES.filter(d=>d.kind==='middle').length}</strong><span>middle powers</span></div><div class="summary-card"><strong>${COOPERATION.filter(d=>d.source&&d.year<=state.year).length}</strong><span>bilateral records</span></div><div class="summary-card"><strong>${COOPERATION.filter(d=>d.members&&d.year<=state.year).length}</strong><span>frameworks</span></div><div class="summary-card"><strong>${CORRIDORS.length}</strong><span>corridors</span></div></div><h3>Cooperation mode</h3><p>Formal bilateral frameworks and selected multilateral supply-chain initiatives.</p><h3>Dependence mode</h3><p>Directions of complementarity or vulnerability across equipment, materials, fabrication, packaging, design, capital, and critical inputs.</p><div class="method-banner">Select a country node or use the menu. Click role labels above the map to filter the value chain.</div>`;return;}
    const d=byId.get(state.selected),agreements=COOPERATION.filter(a=>a.year<=state.year&&(a.source?(a.source===d.id||a.target===d.id):a.members?.includes(d.id))),roles=d.roles.map(r=>`<span class="role-tag" style="background:${ROLE_META[r].color}">${ROLE_META[r].label}</span>`).join('');
    panel.innerHTML=`<h2>${d.name}</h2><div class="role-row">${roles}</div><p><strong>${d.headline}</strong></p><p>${d.strategy}</p><h3>Integrated-circuit trade</h3>${tradeHtml(d)}<h3>Strategic exposure</h3>${exposure(d.exposure)}<h3>Principal strengths</h3><ul class="clean-list">${d.strengths.map(x=>`<li>${x}</li>`).join('')}</ul><h3>Key dependencies</h3><ul class="clean-list">${d.dependencies.map(x=>`<li>${x}</li>`).join('')}</ul><h3>Cooperation records</h3>${agreements.length?agreements.map(agreement).join(''):'<div class="empty">No coded agreement in the current release.</div>'}<div class="method-banner">“Middle power” is an analytical project category. Country roles and exposure scores are transparent research codings.</div>`;
    const b=document.getElementById('loadTrade');if(b)b.addEventListener('click',()=>loadTrade(d));
  }
  async function total(code,flow){const q=new URLSearchParams({period:String(state.year),reporterCode:String(code),cmdCode:'8542',flowCode:flow,partnerCode:'0',partner2Code:'0',customsCode:'C00',motCode:'0',maxRecords:'500'}),r=await fetch(`https://comtradeapi.un.org/public/v1/preview/C/A/HS?${q}`);if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json(),rows=Array.isArray(j.data)?j.data:[];const v=rows.reduce((s,x)=>s+Number(x.primaryValue??x.TradeValue??x.tradeValue??0),0);if(!v)throw new Error('no reported value');return v;}
  async function loadTrade(d){const b=document.getElementById('loadTrade');if(b){b.disabled=true;b.textContent='Loading…';}const k=`${d.id}-${state.year}`;try{const [exports,imports]=await Promise.all([total(d.code,'X'),total(d.code,'M')]);state.trade.set(k,{exports,imports});}catch(e){state.trade.set(k,{error:e.message||'API unavailable'});}renderPanel();}
  function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1}).format(v);}
  init();
})();
