const ROLE_META={equipment:{label:'Equipment',color:'#2e7d32'},materials:{label:'Materials',color:'#00897b'},design:{label:'Design & IP',color:'#7b1fa2'},fabrication:{label:'Fabrication',color:'#c62828'},packaging:{label:'Packaging & Test',color:'#e65100'},assembly:{label:'Electronics Assembly',color:'#1565c0'},capital:{label:'Capital & Infrastructure',color:'#6d4c41'},research:{label:'Research & Talent',color:'#5e35b1'},minerals:{label:'Critical Inputs',color:'#546e7a'}};
const C=(id,name,code,lat,lon,score,kind,roles,dominant,headline,strengths,dependencies,strategy,exposure)=>({id,name,code,lat,lon,score,kind,roles,dominant,headline,strengths,dependencies,strategy,exposure});
const COUNTRIES=[
C('nld','Netherlands',528,52.1,5.3,92,'middle',['equipment','research'],'equipment','A lithography and semiconductor-equipment chokepoint with unusually high leverage over advanced fabrication.',['EUV and DUV lithography ecosystem','Precision equipment and metrology','Dense university–industry research networks'],['Asian foundry demand','U.S.-origin technology and policy coordination','Specialized global component suppliers'],'Leverage through specialization, combined with growing export-control and supply-chain coordination.',{us:4,china:3,eu:5,asia:5}),
C('jpn','Japan',392,36.2,138.3,95,'middle',['equipment','materials','fabrication'],'materials','A broad upstream power whose firms remain indispensable in materials, equipment, sensors, and power semiconductors.',['Photoresists, wafers, gases, and specialty chemicals','Semiconductor production equipment','Power, automotive, and image-sensor chips'],['External leading-edge foundry capacity','Regional demand in China, Taiwan, and Korea','Allied technology coordination'],'Rebuild domestic fabrication while using upstream strengths to anchor trusted international partnerships.',{us:4,china:4,eu:3,asia:5}),
C('kor','South Korea',410,36.4,127.8,96,'middle',['fabrication','materials','assembly'],'fabrication','A memory and fabrication powerhouse whose export model creates deep exposure to external markets and equipment suppliers.',['DRAM and NAND memory','Advanced logic and foundry investment','Large electronics conglomerates'],['Foreign lithography and production equipment','Chinese and global electronics demand','Imported specialty materials and design tools'],'Protect scale advantages while diversifying markets, suppliers, and research partnerships.',{us:4,china:5,eu:4,asia:5}),
C('twn','Taiwan',490,23.7,121,100,'middle',['fabrication','design','packaging'],'fabrication','The central advanced-foundry node in the global network, with exceptional productive power and concentrated geopolitical risk.',['Leading-edge contract fabrication','Fabless design ecosystem','Advanced packaging and testing'],['Foreign equipment, software, and materials','Global customers and intellectual property','Stable cross-strait and maritime access'],'Maintain technological leadership while internationalizing selected capacity without hollowing out the home ecosystem.',{us:5,china:5,eu:4,asia:5}),
C('sgp','Singapore',702,1.35,103.8,82,'middle',['fabrication','packaging','assembly','research'],'packaging','A trusted regional hub combining wafer fabrication, equipment, logistics, headquarters, and advanced manufacturing services.',['Mature-node and specialty fabrication','Equipment and supply-chain operations','Regional coordination and skilled labor'],['Cross-border Malaysian production networks','Global multinational investment','Open maritime trade'],'Preserve hub status through neutrality, reliability, talent, and dense multinational production networks.',{us:4,china:4,eu:3,asia:5}),
C('mys','Malaysia',458,4.2,102,79,'middle',['packaging','assembly','materials'],'packaging','A major assembly, testing, and electronics-production center moving toward higher-value packaging and design functions.',['Outsourced assembly and test','Electronics manufacturing clusters','Penang and Johor industrial ecosystems'],['Imported wafers and advanced equipment','Multinational firms and external demand','Singapore-linked logistics and services'],'Move upward from volume assembly toward advanced packaging, design services, and ecosystem depth.',{us:4,china:4,eu:3,asia:5}),
C('ind','India',699,22.8,79,72,'middle',['design','packaging','research','fabrication'],'design','A large design and talent base attempting to convert market size and subsidies into fabrication and packaging capacity.',['Chip design and engineering talent','Large electronics market','Expanding public incentives and partnerships'],['Imported chips and production equipment','Foreign process technology and anchor investors','Reliable infrastructure and specialized workforce expansion'],'Use market scale and strategic partnerships to acquire missing manufacturing capabilities.',{us:5,china:4,eu:3,asia:5}),
C('vnm','Vietnam',704,16.2,106.3,61,'middle',['assembly','packaging'],'assembly','An electronics-assembly platform seeking a larger role in chip packaging, testing, and engineering services.',['Large electronics export base','Competitive manufacturing labor','Growing packaging and testing investment'],['Imported intermediate components','Foreign-invested production','Regional logistics and technology transfer'],'Leverage electronics assembly to attract higher-value semiconductor back-end functions.',{us:4,china:5,eu:2,asia:5}),
C('isr','Israel',376,31.5,34.9,76,'middle',['design','research','fabrication'],'design','A high-intensity design and R&D ecosystem integrated closely with U.S. firms and global fabrication networks.',['Chip architecture and design','Cyber, sensing, and AI accelerators','Multinational R&D centers'],['External high-volume fabrication','U.S. corporate and security relationships','Global venture and talent networks'],'Convert research intensity into specialized design leadership while relying on trusted external manufacturing.',{us:5,china:2,eu:3,asia:4}),
C('tur','Türkiye',792,39,35.2,45,'middle',['design','research','assembly'],'design','An emerging defense-electronics and design ecosystem with ambitions in specialized and domestically controlled chips.',['Defense and embedded systems','University research and design initiatives','Large manufacturing base'],['Imported advanced chips and tools','Limited fabrication scale','External licensing and process know-how'],'Prioritize strategic niches and trusted access rather than attempting full-stack autonomy.',{us:4,china:3,eu:5,asia:3}),
C('are','United Arab Emirates',784,24.3,54.4,64,'middle',['capital','research'],'capital','A capital-rich technology entrant using investment, infrastructure, and strategic alignment to obtain advanced compute access.',['Sovereign investment capacity','Energy and data-center infrastructure','Rapid institution-building'],['External chips, cloud platforms, and technical talent','Conditional access to frontier technology','Foreign implementation partners'],'Managed dependence: exchange capital, energy, and market access for conditional entry into trusted technology ecosystems.',{us:5,china:3,eu:3,asia:4}),
C('sau','Saudi Arabia',682,24,45,58,'middle',['capital','research'],'capital','A large-scale investor seeking compute, data-center, and technology capabilities as part of economic diversification.',['Capital and energy abundance','Large state-led development programs','Potential regional market scale'],['Imported semiconductors and platforms','Foreign firms and skilled labor','Technology-access conditions'],'Use procurement and investment scale to build bargaining leverage while developing complementary domestic assets.',{us:5,china:3,eu:3,asia:4}),
C('gbr','United Kingdom',826,54.5,-2.5,74,'middle',['design','research','materials'],'design','A design, intellectual-property, compound-semiconductor, and research power with limited high-volume fabrication.',['Processor architecture and IP','Compound semiconductors','Research universities and prototyping'],['External high-volume fabs','Foreign ownership and investment','Asian manufacturing networks'],'Protect high-value design and research niches through partnerships rather than replicate the entire value chain.',{us:5,china:3,eu:5,asia:5}),
C('aus','Australia',36,-25.3,133.8,49,'middle',['minerals','research'],'minerals','An upstream and research partner whose relevance lies in critical minerals, trusted supply, and alliance-based technology cooperation.',['Critical mineral resources','Trusted-alliance position','University and quantum research'],['External refining and chip production','Foreign capital and technology','Asian export markets'],'Convert resource endowments into processing, research, and trusted-supply-chain roles.',{us:5,china:5,eu:3,asia:5}),
C('can','Canada',124,56.1,-106.3,55,'middle',['design','research','minerals'],'research','A research-intensive and resource-rich partner with specialized design, photonics, AI, and compound-semiconductor capabilities.',['AI and university research','Photonics and specialized chip design','Critical minerals and North American integration'],['U.S.-centered commercialization','External advanced fabrication','Scale-up capital and manufacturing capacity'],'Use North American integration and research strengths to secure specialized positions in trusted supply chains.',{us:5,china:3,eu:3,asia:4}),
C('usa','United States',842,38,-97,100,'anchor',['design','equipment','research','fabrication'],'design','External anchor: design software, advanced chip firms, equipment, finance, and technology-access policy.',['Design and EDA','Equipment and research','Large market and policy leverage'],['Asian fabrication and packaging','Allied equipment and materials'],'Anchor node.',{us:0,china:4,eu:4,asia:5}),
C('chn','China',156,35.9,104.2,100,'anchor',['fabrication','assembly','materials'],'assembly','External anchor: the largest electronics-production base and a rapidly expanding semiconductor ecosystem.',['Electronics manufacturing scale','Large domestic market','Expanding mature-node fabrication'],['Advanced equipment and leading-edge chips','Selected foreign materials and software'],'Anchor node.',{us:5,china:0,eu:4,asia:5}),
C('eun','European Union',null,50.8,10.5,95,'anchor',['equipment','materials','research'],'equipment','External anchor: regulatory coordination, industrial subsidies, equipment, automotive demand, and research capacity.',['Equipment and industrial chips','Research networks','Regulatory and subsidy coordination'],['Asian leading-edge production','U.S. design and software'],'Anchor node.',{us:4,china:4,eu:0,asia:5})];
const COOPERATION=[
{id:'nld-kor-2023',source:'nld',target:'kor',year:2023,type:'alliance',status:'active',title:'Netherlands–Republic of Korea Semiconductor Alliance',detail:'Government, business, and university cooperation, including a bilateral dialogue and talent program.',url:'https://www.government.nl/documents/2023/12/13/joint-statement-between-the-government-of-the-republic-of-korea-and-the-government-of-the-kingdom-of-the-netherlands'},
{id:'gbr-jpn-2023',source:'gbr',target:'jpn',year:2023,type:'rd',status:'active',title:'UK–Japan Semiconductors Partnership',detail:'Joint research, skills exchanges, infrastructure access, industry dialogue, and supply-chain resilience.',url:'https://www.gov.uk/government/publications/uk-japan-semiconductors-partnership-joint-statement'},
{id:'gbr-kor-2023',source:'gbr',target:'kor',year:2023,type:'rd',status:'active',title:'UK–Republic of Korea Framework for Semiconductor Cooperation',detail:'Skills, collaborative R&D, industry links, and bilateral and multilateral supply-chain cooperation.',url:'https://www.gov.uk/government/publications/uk-republic-of-korea-framework-for-semiconductor-cooperation-joint-statement/uk-republic-of-korea-framework-for-semiconductor-cooperation-joint-statement'},
{id:'ind-jpn-2023',source:'ind',target:'jpn',year:2023,type:'supply',status:'active',title:'Japan–India Semiconductor Supply Chain Partnership',detail:'A policy framework to strengthen supply-chain resilience and business cooperation.',url:'https://www.meti.go.jp/english/press/2023/0721_002.html'},
{id:'ind-sgp-2024',source:'ind',target:'sgp',year:2024,type:'ecosystem',status:'active',title:'India–Singapore Semiconductor Ecosystem Partnership',detail:'Connects Singapore firms and supply chains with India’s expanding semiconductor ecosystem.',url:'https://www.mti.gov.sg/newsroom/singapore-and-india-sign-memorandum-of-understanding-on-india-singapore-semiconductor-ecosystem-partnership/'},
{id:'jpn-are-2023',source:'jpn',target:'are',year:2023,type:'investment',status:'active',title:'Japan–UAE Semiconductor and Battery Cooperation',detail:'A consultation framework intended to identify semiconductor projects and attract UAE investment into Japan.',url:'https://www.meti.go.jp/english/press/2023/0724_001.html'},
{id:'ind-nld-2026',source:'ind',target:'nld',year:2026,type:'ecosystem',status:'active',title:'India–Netherlands Partnership on Semiconductors and Emerging Technology',detail:'Investment, research, talent exchange, competence-center links, and university–industry collaboration.',url:'https://www.government.nl/documents/2026/05/16/joint-statement-by-india-and-the-netherlands'},
{id:'ipef-2024',members:['aus','ind','jpn','kor','mys','sgp','vnm'],year:2024,type:'multilateral',status:'active',title:'IPEF Supply Chain Agreement',detail:'A multilateral resilience framework with a Supply Chain Council and Crisis Response Network.',url:'https://www.mti.gov.sg/trade-international-economic-relations/regional-and-international-platforms/indo-pacific-economic-framework/ipef-pillars-and-agreements/supply-chain-agreement/'},
{id:'pax-silica-2025',members:['aus','isr','jpn','kor','nld','sgp','gbr','are','ind'],year:2025,type:'multilateral',status:'evolving',title:'Pax Silica trusted-technology initiative',detail:'A U.S.-led framework spanning critical minerals, semiconductors, advanced manufacturing, compute, and infrastructure. Membership is evolving.',url:'https://www.publicnow.com/view/E0691540FEF34C4D71231E6A97D1918816240B01'}];
const CORRIDORS=[['nld','twn','equipment',5,'Lithography and advanced production equipment'],['nld','kor','equipment',5,'Lithography and fab equipment'],['jpn','twn','materials',5,'Wafers, chemicals, materials, and equipment'],['jpn','kor','materials',5,'Materials and production equipment'],['twn','usa','fabrication',5,'Foundry services for U.S.-centered design ecosystem'],['kor','chn','fabrication',5,'Memory and components into electronics production'],['kor','vnm','assembly',4,'Components into electronics manufacturing'],['twn','mys','packaging',4,'Wafers and components into back-end production'],['sgp','mys','packaging',4,'Cross-border manufacturing and logistics ecosystem'],['mys','sgp','assembly',4,'Back-end production linked to regional hub services'],['jpn','ind','equipment',3,'Equipment, materials, and ecosystem development'],['sgp','ind','packaging',3,'Firm participation and supply-chain development'],['usa','isr','design',5,'Corporate R&D, design, and venture integration'],['usa','gbr','design',4,'Design, IP, research, and investment links'],['usa','can','research',4,'North American research and commercialization'],['aus','jpn','minerals',3,'Critical inputs and trusted upstream supply'],['aus','kor','minerals',3,'Critical inputs for advanced manufacturing'],['are','jpn','capital',3,'Sovereign investment and industrial cooperation'],['are','usa','capital',5,'Conditional access to compute and trusted infrastructure'],['sau','usa','capital',4,'Technology procurement, compute, and infrastructure investment'],['ind','usa','design',5,'Design talent, firms, and technology partnership'],['tur','eun','assembly',3,'Industrial integration and imported advanced components']].map(([source,target,layer,intensity,label])=>({source,target,layer,intensity,label}));
